- name: configure backend server
  hosts: backend
  become: yes
  tasks:
  - name: disble current node.js
    ansible.builtin.command: dnf module disable nodejs -y

  - name: install nodejs 20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs 
    ansible.builtin.paackage:
      name: nodejs
      state: present

      
